# Generated by Django 5.2.1 on 2025-05-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaonline_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to='produtos/'),
        ),
    ]
